secret_key = None # Secret key goes here
email_account = 'automation@mozilla.com'
email_password = None # Email's password goes here
email_from = 'Mozilla A-Team <auto-tools@mozilla.com>'
hostname = 'http://localhost:5000'
mysql_user = 'root'
mysql_password = ''
mysql_dbname = 'pulseguardian'
warn_queue_size = 20
archive_queue_size = 150
del_queue_size = 200
polling_interval = 0.5
